import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main>
          <h2>Next Home Page</h2>
          <p>
            Next Lab - Page based routing
          </p>
          <ul>
            <li>
              <Link href="/customer">Customer Page</Link>
            </li>
            <li>
              <Link href="/food">Food Page</Link>
            </li>
            <li>
              <Link href="/cities">Cities Page</Link>
            </li>
            <li>
              <Link href="/receipe">Receipe Page</Link>
            </li>
          </ul>
        </main>
      </div>
    </>
  );
}
